name: pipeline

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          export DOCKER_TAG="${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}:latest"
          docker build . --file Dockerfile --tag "${DOCKER_TAG}"
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}"
