name: pipeline

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_ORG }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
