name: release

on:
  release:
    types: [published, edited]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF_SLUG})
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        env:
          TERRAFORM_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          push: true
          repository: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
          tags: ${{ env.RELEASE_VERSION }}
          build-args: TERRAFORM_VERSION
